# -*- coding: utf-8 -*-
"""Copia de chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9rfElUZH_MPSE43NabVlvO18t3a1vi5
"""

# ── Instalar la librería de HuggingFace ──────────────────
!pip install -q requests
import requests
import json
print("✓ Listo para conectar a HuggingFace")

# ── TU TOKEN de HuggingFace ──────────────────────────────
# Ve a huggingface.co → Settings → Access Tokens → New Token
HF_TOKEN = "TU_Token_Aqui" # ← REEMPLAZA con tu token real

# ── Modelo a usar (gratuito) ─────────────────────────────
MODELO = "HuggingFaceH4/zephyr-7b-beta"
API_URL = f"https://api-inference.huggingface.co/models/{MODELO}"
HEADERS = {"Authorization": f"Bearer {HF_TOKEN}"}

print(f"✓ Modelo configurado: {MODELO}")
print(f"✓ URL de la API: {API_URL}")

# ── Función para llamar al modelo con historial ────────────────────────
def llamar_modelo(mensaje, historial, temperatura=0.7, max_tokens=200):
    # Formateamos el mensaje para que el modelo entienda el contexto
    prompt = f"System: Eres un asistente útil y educado.\n"
    for user_msg, bot_msg in historial:
        prompt += f"User: {user_msg}\nAssistant: {bot_msg}\n"
    prompt += f"User: {mensaje}\nAssistant:"

    payload = {
        "inputs": prompt,
        "parameters": {
            "temperature": temperatura,
            "max_new_tokens": max_tokens,
            "return_full_text": False
        }
    }

    respuesta = requests.post(API_URL, headers=HEADERS, json=payload)

    if respuesta.status_code == 200:
        return respuesta.json()[0]["generated_text"].split("User:")[0].strip()
    else:
        return f"Error {respuesta.status_code}: {respuesta.text}"

# ── Milestone 4: Bucle de conversación interactivo ──────────────────────
historial_chat = []
print("🤖 Chatbot iniciado. Escribe 'salir' para terminar.")

# Realizaremos los 5 turnos de conversación aquí
for i in range(5):
    usuario = input(f"Turno {i+1} - Tú: ")
    if usuario.lower() == "salir":
        break

    respuesta_bot = llamar_modelo(usuario, historial_chat)
    print(f"Chatbot: {respuesta_bot}\n")

    # Guardamos en la memoria
    historial_chat.append((usuario, respuesta_bot))

print("✓ Conversación finalizada.")

# ── Bucle de conversación ───────────────────────────────
print("Chatbot activo (escribe 'salir' para terminar)")
while True:
    usuario = input("Tú: ")
    if usuario.lower() == "salir":
        break
    respuesta = llamar_modelo(usuario)
    print(f"Chatbot: {respuesta}")

# ── Milestone 5: Estadísticas ──────────────────────────
total_palabras = sum(len(u.split()) + len(b.split()) for u, b in historial_chat)
print(f"📊 Estadísticas de la sesión:")
print(f"- Turnos completados: {len(historial_chat)}")
print(f"- Total de palabras procesadas: {total_palabras}")